apiVersion: v1
kind: Namespace
metadata:
  name: minecraft
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-test-server-deployment
  namespace: minecraft
  labels:
    app: mc-test-server
spec:
  selector:
    matchLabels:
      app: mc-test-server
  replicas: 1
  template:
    metadata:
      labels:
        app: mc-test-server
    spec:
      containers:
      - name: mc-test-server-container
        image: itzg/minecraft-server
        env:
        - name: EULA
          value: "TRUE"
        - name: VERSION
          value: "1.20.1"
        - name: TYPE
          value: "PAPER"
        - name: MEMORY
          value: "3G"
        ports:
        - containerPort: 25565
        volumeMounts:
        - name: mc-test-server-storage
          mountPath: "/data"
      volumes:
      - name: mc-test-server-storage
        nfs:
          server: 192.168.1.110
          path: /home/mc/test-server/gamefiles
---
apiVersion: v1
kind: Service
metadata:
  name:  mc-test-server-service-nodeport
  namespace: minecraft
spec:
  selector:
    app:  mc-test-server
  type:  NodePort
  ports:
  - name:  game-port
    port:  25565
    nodePort: 32000
    protocol: TCP
